# Core Colors
background            #1a120e
foreground            #f0dfd8
selection_foreground  #ffb692
selection_background  #542103
cursor                #ffb692
cursor_text_color     #1a120e

# Regular Colors
color0  #1a120e
color1  #ffb4ab
color2  #ffb692
color3  #cfc890
color4  #ffdbcb
color5  #ffdbcb
color6  #e6beac
color7  #f0dfd8

# Bright Colors
color8  #423732
color9  #ffb4ab
color10 #ffb692
color11 #cfc890
color12 #ffdbcb
color13 #ffdbcb 
color14 #e6beac
color15 #f0dfd8
