############################
# APPLICATIONS BLUR
############################

windowrule = noblur, tag:multimedia_video*
windowrule = opacity 1.0, tag:multimedia_video*
windowrule = opacity 0.8, tag:settings*

# File manager (Wayland)
windowrule = opacity 0.8, app_id:org.gnome.Nautilus

# Text editors
windowrule = opacity 0.9, classRegex:^(gedit|mousepad)$
windowrule = opacity 0.9, app_id:org.gnome.TextEditor

# Audio control
windowrule = opacity 0.9, classRegex:^(org\.pulseaudio\.pavucontrol)$

# Terminal
windowrule = opacity 0.9, classRegex:^(kitty)$

# Chat apps
windowrule = opacity 0.85 override 0.7 override 1 override, classRegex:^(discord|vesktop|org\.telegram\.desktop)$

# Spotify
windowrule = opacity 0.8 override 0.6 override 1 override, classRegex:^(Spotify)$

# Zen browser
# windowrule = opacity 0.9 override 0.7 override 1 override, classRegex:^(zen)$
# windowrule = float, class:^(zen)$ title:^(Picture-in-Picture)$
# Picture-in-Picture
windowrule = float, title:^(Picture-in-Picture)$


# Stremio
windowrule = opacity 1.0 override 1.0 override 1.0 override, classRegex:^(com\.stremio\.stremio)$


############################
# LAYER RULES
############################


############################
# FLOATING RULES
############################

windowrule = float, tag:settings*
windowrule = float, tag:viewer*
windowrule = float, tag:multimedia_video*
windowrule = size 900 506, tag:multimedia_video*

# Pavucontrol
windowrule = float, classRegex:^(org\.pulseaudio\.pavucontrol)$
windowrule = size 50% 60%, classRegex:^(org\.pulseaudio\.pavucontrol)$


############################
# MISC FIXES
############################

# Ignore maximize requests
windowrule = suppressevent maximize, classRegex:.*

# Fix XWayland dragging issues
# windowrule = nofocus, xwayland:1, floating:1, fulls


